// Generated by CoffeeScript 1.3.3
(function() {

  describe('ExerciseModal', function() {
    beforeEach(function() {
      loadFixtures("exercise_listed_in_workout.html");
      this.modal = new ExerciseModal;
      this.modal.init();
      return this.link = $('a.exercise_ajax_modal');
    });
    return describe('click link', function() {
      return it('sets the target_link', function() {
        this.link.click();
        return expect(this.modal.target_link).toEqual(this.link);
      });
    });
  });

}).call(this);
