class window.AddExerciseToWorkout

  constructor: (@link, @template_renderer = new HoganTemplateBuilder) ->
    @params   = $.param( { workout_exercise: { workout_id: @link.data('workout_id'), exercise_id: @link.data('exercise_id') } })
    @mustache = 'app/templates/workout_exercises/show'

  init: ->
    @link.on 'click', (event) =>
      event.preventDefault()
      @createWorkoutExercise()

  createWorkoutExercise: =>
    $.ajax {
      url: "/workout_exercises?#{@params}",
      type: 'POST',
      dataType: 'json',

      success: (workout_exercise) => @updateWorkout(workout_exercise)

      failure: => alert('Sorry something went wrong! Try again...')
    }

  updateWorkout: (workout_exercise) =>
    $(@link).parent($( 'h4' )).effect('highlight', {}, 4500)
    # @link.fadeOut 100, -> $(this).text('Exercise Added!').fadeIn(500)
    @link.next('p').text('Exercise Added!').fadeIn(200).fadeOut(4500)
    $( 'ul.workout_exercises' ).append(@template_renderer.render(@mustache, workout_exercise))

# need to listen when DOM nodes are inserted because the
# ADD exercise to workout link is generated by ExerciseModalLoader
if $('.modal#add_workout_exercise')
  document.body.addEventListener "DOMNodeInserted", (event) =>
    @element  = $( event.target )
  
    if element.hasClass('exercise_list_item')
      @link = $(@element).find('a.add_exercise_to_workout_button')
      if @link.length > 0
        add_exercise_to_workout = new AddExerciseToWorkout @link
        add_exercise_to_workout.init()