development:
  adapter: sqlite3
  prepared_statements: false
  database: db/development.sqlite3
  pool: 5
  timeout: 5000

test:
  adapter: sqlite3
  prepared_statements: false
  database: db/test<%= ENV['TEST_ENV_NUMBER'] %>
  pool: 5
  timeout: 5000

# development:
#   adapter: postgresql
#   encoding: utf8
#   database: fitafy_development
#   pool: 5
#   username: vladiim
#   password:
#   host: localhost

# test:
#   adapter: postgresql
#   encoding: utf8
#   database: fitafy_test
#   pool: 5
#   username: vladiim
#   password:
#   host: localhost