development:
  adapter: postgresql
  encoding: utf8
  database: fitafy_development
  pool: 5
  username: vladiim
  password:
  host: localhost

test:
  adapter: postgresql
  encoding: utf8
  database: fitafy_test
  pool: 5
  username: vladiim
  password:
  host: localhost